# When working locally, uncomment the "ipfs" service and the "depends_on" line in server
version: '3.8'
services:
  ipfs:
    image: ipfs/kubo:master-2024-04-17-eb97cf9
    ports:
      - "5001:5001" # API port
      - "8080:8080" # Gateway port
      - "4001:4001" # Swarm port
    environment:
      - LIBP2P_FORCE_PNET=1
    volumes:
      - ipfs_staging:/export
      - ipfs_data:/data/ipfs
      - ${PWD}/ipfs/swarm.key:/data/ipfs/swarm.key
      - ${PWD}/ipfs/init.sh:/container-init.d/ipfs-init.sh
    healthcheck:
      test: ["CMD", "ipfs", "id"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REBUILD: ${REBUILD:-1}
    ports:
      - "5002:5000"
    depends_on:
      ipfs:
        condition: service_healthy
    # when working locally, comment this out
    # network_mode: "host"
    environment:
    # when working locally, change IPFS_HOST to 'ipfs'
      - IPFS_HOST=ipfs
      - IPFS_PORT=5001
      - IPFS_GATEWAY=https://ipfs.io
    volumes:
      - ./data:/data
      - ./src:/app
    command: gunicorn --bind 0.0.0.0:5000 --timeout 300 app:app

volumes:
  ipfs_staging:
  ipfs_data: